/** Query methods whose lambda arguments are expression positions. */
export const QUERY_METHODS: ReadonlySet<string> = new Set([
  "filter",
  "map",
  "orderBy",
  "orderByDescending",
  "thenBy",
  "thenByDescending",
  "groupBy",
  "count",
  "some",
  "every",
  "first",
  "firstOrThrow",
  "single",
  "sum",
  "min",
  "max",
  "avg",
  "join",
  "leftJoin",
  "flatMap",
]);
