#!/usr/bin/env node
// Generates the two docs pages that must never be hand-edited: the diagnostics
// reference (from the capture catalog) and the tree JSON-schema page (from the
// tree types). Run before building the docs site. Requires packages built.

import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { DIAGNOSTICS } from "@treequel/capture";
import { treeJsonSchema, FORMAT_VERSION } from "@treequel/tree";

const docs = join(dirname(fileURLToPath(import.meta.url)), "..", "apps", "docs");
const banner = "<!-- Generated by scripts/gen-docs.mjs — do not edit by hand. -->\n\n";

const ranges = [
  ["R11", "Capture — the expression subset"],
  ["R19", "Tree format"],
  ["R20", "Providers & query plans"],
  ["R30", "Runtime fallback"],
  ["R40", "Build plugin & config"],
];

const codes = Object.keys(DIAGNOSTICS).sort();

let errors = `${banner}# Error reference

Every Treequel diagnostic has a stable code. Codes are append-only: they are never renumbered or reused, and each keeps
this anchor (\`#R1101\`) so build errors, editor squiggles, and lint output can link straight here.
`;

for (const [prefix, title] of ranges) {
  const group = codes.filter((c) => c.startsWith(prefix));
  if (group.length === 0) continue;
  errors += `\n## ${title}\n`;
  for (const code of group) {
    const d = DIAGNOSTICS[code];
    errors += `\n### ${code} {#${code}}\n\n`;
    errors += `**${d.severity}** — ${d.summary}.\n`;
    if (d.hint) errors += `\n> ${d.hint}\n`;
  }
}

writeFileSync(join(docs, "errors.md"), errors);

const schemaPage = `${banner}# Tree JSON schema

The expression-tree wire format is a small, closed, versioned discriminated union. This page is generated from the
\`@treequel/tree\` types; the current format version is **${FORMAT_VERSION}**. A serialized tree is a
\`{ v, root }\` envelope; the deserializer refuses a \`v\` newer than it understands.

Non-TypeScript consumers (a Go or .NET server rehydrating a remote query) can validate against this schema.

\`\`\`json
${JSON.stringify(treeJsonSchema, null, 2)}
\`\`\`
`;

mkdirSync(join(docs, "reference"), { recursive: true });
writeFileSync(join(docs, "reference", "tree-schema.md"), schemaPage);

console.log(`Generated errors.md (${codes.length} codes) and reference/tree-schema.md.`);
